[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://shikshavaani-ai-ym58.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"